import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import WidthWrapper from "@/components/WidthWrapper";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ weight: ["400", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <WidthWrapper>
          <Nav />
          {children}
          <Footer />
        </WidthWrapper>
        <Toaster />
      </body>
    </html>
  );
}
